/**
 * BODY — the six placeholder feedback cues (Cycle 01, Stage 2).
 *
 * Every core action is audible as well as visible (charter §I.18 rule 1), and every cue
 * is mirrored by something on screen so the game is fully playable on mute (rule 7).
 * The files are generated by tools/gen-audio.mjs — ours, licence-free, regenerable.
 */

import { Scene } from 'phaser';

export const CUES = {
    /** A node comes into reach / is designated. */
    target: 'target',
    /** Driftwood snatched off the sand. */
    pickup: 'pickup',
    /** Deadfall salvage in progress (loops under the hold ring). */
    gather: 'gather',
    /** Wood lands in the pack and the count changes. */
    collected: 'collected',
    /** The fire catches. */
    ignition: 'ignition',
    /** The fire burning (loops while lit). */
    fireloop: 'fireloop',
    /** Not enough wood. */
    denied: 'denied'
} as const;

export type CueKey = (typeof CUES)[keyof typeof CUES];

const VOLUME: Record<CueKey, number> = {
    target: 0.35,
    pickup: 0.55,
    gather: 0.45,
    collected: 0.6,
    ignition: 0.7,
    fireloop: 0.3,
    denied: 0.5
};

export function preloadCues(scene: Scene): void {
    for (const key of Object.values(CUES)) {
        scene.load.audio(key, `assets/audio/${key}.wav`);
    }
}

/**
 * Thin wrapper over the SoundManager: one-shots are fire-and-forget, the two beds
 * (gather, fireloop) are retained so they can be started and stopped precisely.
 */
export class Cues {
    private beds = new Map<CueKey, Phaser.Sound.BaseSound>();

    constructor(private readonly scene: Scene) {}

    play(key: CueKey): void {
        if (!this.scene.sound) return;
        this.scene.sound.play(key, { volume: VOLUME[key] });
    }

    startBed(key: CueKey): void {
        if (!this.scene.sound) return;
        let bed = this.beds.get(key);
        if (!bed) {
            bed = this.scene.sound.add(key, { loop: true, volume: VOLUME[key] });
            this.beds.set(key, bed);
        }
        if (!bed.isPlaying) bed.play();
    }

    stopBed(key: CueKey): void {
        const bed = this.beds.get(key);
        if (bed?.isPlaying) bed.stop();
    }

    stopAllBeds(): void {
        for (const key of this.beds.keys()) this.stopBed(key);
    }
}
